package com.app.expensecontroller.examandroid;

public class Utilidades {

    public static final String TABLA_ESTABLECIMIENTO="CREATE TABLE ESTABLECIMIENTO" +
            "(ID_ESTABLECIMIENTO INTENGER NOT NULL PRIMARY KEY AUTOINCREMENT,\n" +
            ", NOMBRE_ESTABLECIMIENTO VARCHAR(100) NOT NULL5,\n " +
            "CIUDAD_ESTABLECIMIENTO VARCHAR(100) NOT NULL,\n" +
            "TIPO_ESTABLECIMIENTO VARCHAR(20) NOT NULL,\n" +
            "NIVEL_ESTABLECIMIENTO VARCHAR(30) NOT NULL)";



    public static final String TABLA_ESTABLECIMIENTOS = "CREATE TABLE ESTABLECIMIENTO (ID_ESTABLECIMIENTO INTEGER PRIMARY KEY AUTOINCREMENT," +
            " NOMBRE_ESTABLECIMIENTO TEXT NOT NULL, CIUDAD_ESTABLECIMIENTO TEXT NOT NULL, TIPO_ESTABLECIMIENTO TEXT NOT NULL, NIVEL_ESTABLECIMIENTO TEXT NOT NULL)";
}
